const appConstants = {
  WEB_REQUEST: 'WEB_REQUEST',
  WEB_REQUEST_SUCCESS: 'WEB_REQUEST_SUCCESS',
  WEB_REQUEST_ERROR: 'WEB_REQUEST_ERROR',
  WEB_REQUEST_TIMEOUT: 'WEB_REQUEST_TIMEOUT',
  LOADING_TYPE_LIST: 'PROJECTS',
  LOADING_TYPE_BULLET_LIST: 'BULLETS',
  HOME: 'HOME',
  PHASES: 'PHASES',
};
export default appConstants;
