const KYCConstants = {
  KYC_CREATE_SUCCESS: 'KYC_CREATE_SUCCESS',
  KYC_CREATE_FAILURE: 'KYC_CREATE_FAILURE',
  KYC_CREATE_FETCH: 'KYC_CREATE_FETCH',
  KYC_GETDETAILS_FETCH:'KYC_GETDETAILS_FETCH',
  KYC_GETDETAILS_SUCCESS:'KYC_GETDETAILS_SUCCESS',
  KYC_GETDETAILS_FAILURE:'KYC_GETDETAILS_FAILURE',
};
export default KYCConstants;
