const PaymentsConstants = {

    PAYMENTS_REDEMPTIONDETAILS_FETCH: 'PAYMENTS_REDEMPTIONDETAILS_FETCH',
    PAYMENTS_REDEMPTIONDETAILS_SUCCESS: 'PAYMENTS_REDEMPTIONDETAILS_SUCCESS',
    PAYMENTS_REDEMPTIONDETAILS_FAILURE: 'PAYMENTS_REDEMPTIONDETAILS_FAILURE',
    PAYMENTS_INPUTPAYMENTDETAILS_FETCH: 'PAYMENTS_INPUTPAYMENTDETAILS_FETCH',
    PAYMENTS_INPUTPAYMENTDETAILS_SUCCESS: 'PAYMENTS_INPUTPAYMENTDETAILS_SUCCESS',
    PAYMENTS_INPUTPAYMENTDETAILS_FAILURE: 'PAYMENTS_INPUTPAYMENTDETAILS_FAILURE',
    PAYMENTS_TRANSFERTRANSACTIONDETAILS_FETCH: 'PAYMENTS_TRANSFERTRANSACTIONDETAILS_FETCH',
    PAYMENTS_TRANSFERTRANSACTIONDETAILS_SUCCESS: 'PAYMENTS_TRANSFERTRANSACTIONDETAILS_SUCCESS',
    PAYMENTS_TRANSFERTRANSACTIONDETAILS_FAILURE: 'PAYMENTS_TRANSFERTRANSACTIONDETAILS_FAILURE',
};
export default PaymentsConstants;