const PaymentsConstants = {

    PAYMENTS_TRANSFERTRANSACTIONDETAILS_FETCH: 'PAYMENTS_TRANSFERTRANSACTIONDETAILS_FETCH',
    PAYMENTS_TRANSFERTRANSACTIONDETAILS_SUCCESS: 'PAYMENTS_TRANSFERTRANSACTIONDETAILS_SUCCESS',
    PAYMENTS_TRANSFERTRANSACTIONDETAILS_FAILURE: 'PAYMENTS_TRANSFERTRANSACTIONDETAILS_FAILURE',
};
export default PaymentsConstants;